blank_issues_enabled: false
contact_links:
  - name: Project Documentation
    url: https://github.com/valtiojs/valtio-auto-persist/#readme
    about: Check our documentation for guides on contributing.